name: Docker

on: [push, pull_request, workflow_dispatch]

env:
  ENDPOINT: "rursache/bird.makeup"
  BRANCH: "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Build image
        run: |
          docker build --no-cache -t ${{ github.sha }} .

      - name: Tag image
        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.ENDPOINT != 'user/endpoint' }}
        run: |
          docker tag ${{ github.sha }} ${ENDPOINT}
          docker tag ${{ github.sha }} ${ENDPOINT}:${{ github.sha }}
          docker tag ${{ github.sha }} ghcr.io/${ENDPOINT}
          docker tag ${{ github.sha }} ghcr.io/${ENDPOINT}:${{ github.sha }}

      - name: Credential check
        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.ENDPOINT != 'user/endpoint' }}
        run: |
          echo "GHUSER=${{ secrets.GHUSER }}" >> $GITHUB_ENV
          echo "GHTOKEN=${{ secrets.GHTOKEN }}" >> $GITHUB_ENV
          if [[ "${{ secrets.GHUSER }}" == "" && "${{ secrets.GHTOKEN }}" == ""]]; then
            echo "::error::Push credential secrets missing."
            echo "::error::You must set GHUSER & GHTOKEN in your repo settings."
            exit 1
          fi

      - name: Login to GitHub Container Registry
        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.GHUSER && env.GHTOKEN && env.ENDPOINT != 'user/endpoint' }}
        run: |
          echo "${{ secrets.GHTOKEN }}" | docker login ghcr.io -u ${{ secrets.GHUSER }} --password-stdin

      - name: Push tags to GitHub Container Registry
        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.GHUSER && env.GHTOKEN && env.ENDPOINT != 'user/endpoint' }}
        run: |
          docker push ghcr.io/${ENDPOINT}:${{ github.sha }}
          docker push ghcr.io/${ENDPOINT}
