name: Sync with SourceHut

on:
  schedule:
      - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.GHTOKEN }}
      
      - name: Sync with SourceHut
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add sourcehut https://git.sr.ht/~cloutier/bird.makeup
          git fetch sourcehut
          git merge -X 'theirs' --no-commit --allow-unrelated-histories sourcehut/master
          git reset -- .github
          git reset -- Dockerfile
          git commit --no-edit
          git push
